const { JSDOM, VirtualConsole } = require('jsdom');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const script = fs.readFileSync(__dirname + '/../dist/readscape-nga.user.js', 'utf8');
const titles = ['[置顶]浪奔浪流 顺应趋势 技术分析 临时讨论 勿转时事', '中国牛市还在！', '自立自强，科学技术打头阵----救赎版', '不得不说，大a的大资金预判是真强，美股科技也涨不动了', '存储人…向南，还是向北', '自从进了股市，我消费降级了 5 倍。', '[中长线躺平流]分享一下我的投资组合(临时)', '真是被场内纳指etf这溢价波动给整笑了'];
const authors = ['zeg', 'erer990127', '-阿狼-', 'Arthdeb', '村上吹树', '小咩太而已啦', '海伯利安之歌', 'ninebluen'];
const counts = [0, 2, 66283, 46, 9610, 19, 10836, 5];
const fixture = `<!doctype html><meta name="viewport" content="width=device-width, initial-scale=1"><title>[股市]技术分析 NGA玩家社区</title><div id="m_nav"><a href="/thread.php?stid=47206901">[股市]技术分析</a></div><div id="m_pbtntop">${[1,2,3,4,5,6].map(p=>`<a href="/thread.php?stid=47206901&page=${p}">${p===1?'1̣':p}</a>`).join('')}</div><table id="topicrows">${titles.map((title,i)=>`<tr class="row1 topicrow"><td class="c1"><a class="replies" href="/read.php?tid=${100+i}">${counts[i]}</a></td><td class="c2"><a class="topic" href="/read.php?tid=${100+i}">${title}</a><span id="t_pc1_${i}"><a href="/read.php?tid=${100+i}&page=2">2</a></span></td><td class="c3"><a class="author" href="/nuke.php?func=ucp&uid=${i}"><b>${authors[i][0]}</b>${authors[i].slice(1)}</a><span class="postdate">今天 13:02</span></td><td class="c4"><a class="replydate" href="/read.php?tid=${100+i}&page=e">5分钟前</a><span class="replyer">其他用户</span></td></tr>`).join('')}</table>`;
const sleep = ms => new Promise(r=>setTimeout(r,ms));
(async () => {
  const errors=[];
  const vc = new VirtualConsole(); vc.on('jsdomError',e=>errors.push(e.message));
  const dom = new JSDOM(fixture,{url:'https://bbs.nga.cn/thread.php?stid=47206901&rand=961',runScripts:'dangerously',virtualConsole:vc});
  const w=dom.window; w.TextDecoder=TextDecoder;
  w.localStorage.setItem('nga-cards-v1',JSON.stringify({enabled:true,autoPreview:true}));
  let fetches=0;
  w.fetch=async()=>{fetches++;throw new Error('列表不应请求首楼');};
  w.eval(script);
  const root=w.document.querySelector('#nga-cards-host').shadowRoot;
  const cards=()=>[...root.querySelectorAll('.card')];
  const click=sel=>root.querySelector(sel).click();
  const search=value=>{const input=root.querySelector('input[type=search]');input.value=value;input.dispatchEvent(new w.Event('input'))};
  assert.equal(cards().length,8);
  assert.equal(root.querySelector('.author').textContent,'zeg');
  assert.match(cards()[2].textContent,/6.6万回复/);
  assert.match(root.querySelector('.latest').href,/page=e/);
  assert.equal(root.querySelectorAll('.pager a').length,0);
  assert.equal(root.querySelector('.list-load').hidden,false,'下一页改为追加加载');
  assert.equal(fetches,0,'旧的自动预览偏好不再触发首楼请求');
  click('button[aria-label="展开或收起搜索"]');assert.equal(root.querySelector('.app').classList.contains('search-open'),true);
  assert.equal(root.querySelector('button[aria-label="展开或收起搜索"]').getAttribute('aria-expanded'),'true');
  click('button[aria-label="展开或收起设置"]');assert.equal(root.querySelector('.app').classList.contains('options-open'),true);
  assert.equal(root.querySelectorAll('.mobile-caption').length,0,'标题只在封面出现一次');
  search('存储'); assert.equal(cards().length,1); search('');
  click('[data-tab=hot]'); assert.equal(cards().length,3);
  click('[data-tab=all]'); cards()[1].querySelector('.save').click();
  click('[data-tab=saved]'); assert.equal(cards().length,1);
  click('[data-tab=all]');
  assert.equal(root.querySelector('.preview'),null,'移除首楼预览入口');
  assert.equal(fetches,0,'筛选和收藏不请求首楼');
  click('.bar .pill'); assert.equal(root.querySelector('.app').hidden,true);
  assert.equal(w.document.documentElement.style.overflow,'');
  click('.restore'); assert.equal(root.querySelector('.app').hidden,false);
  const check=root.querySelector('.settings input');check.checked=true;check.dispatchEvent(new w.Event('change'));
  assert.equal(root.querySelector('.grid').classList.contains('single'),true);
  const r=w.document.querySelector('#topicrows tr:last-child').cloneNode(true);
  r.querySelector('.topic').href='/read.php?tid=999';r.querySelector('.topic').textContent='晚到的动态帖子';
  let confirmList;
  w.fetch=async(url,options)=>{
    fetches++;assert.equal(new URL(url).pathname,'/thread.php');assert.equal(options.cache,'no-cache');
    return new Promise(resolve=>{confirmList=()=>resolve({ok:true,url,headers:{get:()=>''},arrayBuffer:async()=>new TextEncoder().encode(w.document.documentElement.outerHTML).buffer});});
  };
  w.document.querySelector('#topicrows').append(r);await sleep(300);assert.equal(cards().length,8);
  assert.equal(fetches,1);assert(root.querySelector('.list-refresh').hidden,'实际请求完成前不提示新内容');
  confirmList();await sleep(25);assert.equal(root.querySelector('.list-refresh').hidden,false);
  click('.list-refresh');assert.equal(cards().length,9);
  w.close();
  // 使用观察到的访客页原生链接结构，确认一次页面只点击一次且跨页计数。
  let retryState;
  for(let round=0;round<3;round++) {
    const gate=new JSDOM('<title>访客不能直接访问</title><a href="javascript:void(0)" onclick="window.clicked=(window.clicked||0)+1">如不能自动跳转 可点此链接</a><a href="/login">登录</a>',{url:'https://bbs.nga.cn/thread.php?stid=47206901&rand=732',runScripts:'dangerously',virtualConsole:vc});
    const gw=gate.window, key='nga-cards-v1-continue-47206901';
    if(retryState)gw.sessionStorage.setItem(key,retryState);
    gw.eval(script); await sleep(1300);
    assert.equal(gw.clicked||0,round<2?1:0);
    const gr=gw.document.querySelector('#nga-cards-host').shadowRoot;
    assert.equal(gr.querySelector('.app').hidden,true);
    if(round===2)assert.match(gr.textContent,/自动跳转已尝试两次/);
    retryState=gw.sessionStorage.getItem(key);gw.close();
  }
  assert.deepEqual(errors,[]);
  console.log('PASS: 真实字段结构解析、分页、搜索、收藏、无首楼预览请求、原版恢复、单列切换、动态列表、访客自动点击与跨刷新次数上限。');
})().catch(e=>{console.error(e);process.exit(1)});
