const {JSDOM, VirtualConsole} = require('jsdom');
const fs=require('node:fs'), assert=require('node:assert/strict');
const script=fs.readFileSync(__dirname+'/../dist/readscape-nga.user.js','utf8');
const quote=(pid,body='被引用的正文',page=1)=>`<div class="quote"><a href="/read.php?tid=47651896&topid=${pid}&page=${page}#pid${pid}Anchor">+</a><a href="javascript:void(0)" onclick="window.hacked=true">R</a> by <a class="userlink" href="/nuke.php?uid=4">用户四</a><br>${body}</div>`;
const post=(floor,pid,body)=>`<table><tr id="post1strow${floor}"><td><a href="#l${floor}">#${floor}</a><a id="postauthor${floor}" class="author" href="/nuke.php?uid=${floor}">用户${floor}</a></td><td id="postcontainer${floor}"><a id="pid${pid}Anchor"></a><a name="l${floor}"></a><div id="postInfo${floor}"><span id="postdate${floor}">2026-10-01 13:00</span></div><h3 id="postsubject${floor}">${floor===0?'测试帖子':''}</h3><span id="postcontent${floor}" class="postcontent ubbcode">${body}</span></td></tr></table>`;
const fixture=`<title>测试帖子 NGA玩家社区</title><div id="m_nav"><a href="/thread.php?stid=47206901">[股市]技术分析</a></div><div id="pagebtop"><a class="invert">1̣</a></div>${post(0,0,'这是首楼。<img src="https://img4.nga.cn/ngabbs/post/smile/ac15.png" alt="哭笑"><img src="about:blank" style="display:none" onerror="window.hacked=true">')}${post(1,1001,'原始评论<p>第二段</p>')}${post(2,1002,quote(1001)+'第一条回复')}${post(3,1003,quote(1002,quote(1001)+'第一条回复')+'回复的回复')}${post(4,1004,quote(1001)+quote(1002)+'同时引用两条评论')}`;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
  const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
  const dom=new JSDOM(fixture,{url:'https://bbs.nga.cn/read.php?tid=47651896',runScripts:'dangerously',virtualConsole:vc});
  const w=dom.window;w.TextDecoder=TextDecoder;w.HTMLElement.prototype.scrollIntoView=function(){};
  let fetches=0;
  w.fetch=async url=>{fetches++; const p=new URL(url).searchParams.get('page');
    const html=p==='2'?post(20,2001,quote(1001)+'跨页回复')+post(21,2002,'后一页正文<a href="javascript:window.hacked=true">危险链接</a><img src="https://img4.nga.cn/example.png" onerror="window.hacked=true">'):post(21,2002,'重复末页');
    return {ok:true,url,headers:{get:()=> 'text/html; charset=utf-8'},arrayBuffer:async()=>new TextEncoder().encode(html).buffer};
  };
  w.eval(script);const root=w.document.querySelector('#nga-cards-host').shadowRoot;
  assert.equal(root.querySelectorAll('.comment').length,5);
  assert.equal(root.querySelectorAll('.comment.op').length,1);
  assert.equal(root.querySelector('.reader h1').textContent,'测试帖子');
  assert.equal(root.querySelectorAll('.quoted[open]').length,0);
  assert.equal(root.querySelectorAll('img.emoji').length,1);
  assert.equal(root.querySelectorAll('.comment-content [onclick],.comment-content [onerror]').length,0);
  assert.equal(root.querySelectorAll('.comment-content a[href^="javascript:"]').length,0);
  assert.equal(fetches,0);
  root.querySelector('[data-group=true]').click();
  assert.equal(root.querySelectorAll('.thread').length,1);
  assert.match(root.querySelector('.thread>summary').textContent,/2 条/);
  assert.equal(root.querySelectorAll('.thread .comment').length,2);
  assert.equal(root.querySelectorAll('.reader-page>.comment').length,3,'多引用评论不合并');
  root.querySelector('[data-key="pid:1003"] .comment-content > .quoted > .context').click();await sleep(20);
  assert.equal(root.querySelector('.thread').open,true,'上下文定位打开被折叠的对话');
  assert.equal(root.querySelector('[data-key="pid:1002"]').classList.contains('flash'),true);
  root.querySelector('.load-next').click();root.querySelector('.load-next').click();await sleep(30);
  assert.equal(fetches,1,'并发点击只发出一个分页请求');
  assert.equal(root.querySelectorAll('.reader-page').length,2);
  assert.equal(root.querySelectorAll('.comment').length,7);
  assert.equal(root.querySelector('.dock-count').textContent,'评论 6');
  assert.equal(root.querySelectorAll('.comment-actions .action-date').length,7);
  const media=root.querySelector('.attachment');assert.match(media.href,/example\.png/);assert.equal(media.getAttribute('aria-label'),'查看完整图片');
  assert.equal(root.querySelectorAll('.comment.op').length,1);
  assert.equal(root.querySelectorAll('.comment-content [onerror]').length,0);
  root.querySelector('[data-key="pid:2001"] .context').click();await sleep(10);
  assert.equal(fetches,1,'跨页上下文已加载时不再次请求');
  root.querySelector('.load-next').click();await sleep(30);
  assert.equal(root.querySelector('.load-next').disabled,true,'重复页不重复追加');
  assert.equal(root.querySelectorAll('.comment').length,7);
  w.document.querySelector('#postauthor1').textContent='更新后的用户';await sleep(300);
  assert.equal(root.querySelectorAll('.reader-page').length,2,'原站动态更新不抹掉已加载页');
  assert.equal(root.querySelector('[data-key="pid:1001"] .reader-author').textContent,'更新后的用户');
  root.querySelector('.reader .bar button').click();
  assert.equal(root.querySelector('.app').hidden,true);assert.equal(w.document.documentElement.style.overflow,'');
  root.querySelector('.restore').click();assert.equal(root.querySelector('.app').hidden,false);
  root.querySelector('.reply-entry').click();assert.equal(root.querySelector('.app').hidden,true,'移动端回复入口打开原版');
  root.querySelector('.restore').click();assert.equal(root.querySelector('.app').hidden,false);
  assert.deepEqual(errors,[]);assert.equal(w.hacked,undefined);dom.window.close();
  // 错误/登录页不给虚假的“已到末页”，并提供原站入口。
  const failed=new JSDOM(fixture,{url:'https://bbs.nga.cn/read.php?tid=47651896',runScripts:'dangerously',virtualConsole:vc});
  failed.window.TextDecoder=TextDecoder;failed.window.fetch=async url=>({ok:true,url,headers:{get:()=>''},arrayBuffer:async()=>new TextEncoder().encode('<title>访客不能直接访问</title>').buffer});
  failed.window.eval(script);const fr=failed.window.document.querySelector('#nga-cards-host').shadowRoot;fr.querySelector('.load-next').click();await sleep(30);
  assert.equal(fr.querySelector('.load-next').disabled,false);assert.match(fr.querySelector('.reader-status').textContent,/直接打开第 2 页/);failed.window.close();
  const cross=new JSDOM(fixture+post(5,1005,quote(4001,'来自第4页',4)+'跨页引用'),{url:'https://bbs.nga.cn/read.php?tid=47651896',runScripts:'dangerously',virtualConsole:vc});
  cross.window.TextDecoder=TextDecoder;cross.window.HTMLElement.prototype.scrollIntoView=function(){};
  const requested=[];
  cross.window.fetch=async url=>{const p=Number(new URL(url).searchParams.get('page'));requested.push(p);return {ok:true,url,headers:{get:()=>''},arrayBuffer:async()=>new TextEncoder().encode(post(p===4?60:20,p===4?4001:2001,'目标页正文')).buffer}};
  cross.window.eval(script);const cr=cross.window.document.querySelector('#nga-cards-host').shadowRoot;
  cr.querySelector('[data-key="pid:1005"] .context').click();await sleep(30);
  assert.deepEqual(requested,[4]);assert.equal(cr.querySelector('[data-key="pid:4001"]').classList.contains('flash'),true);
  cr.querySelector('.load-next').click();await sleep(30);
  assert.deepEqual(requested,[4,2],'读取跨页引用不会跳过正常的下一页');
  assert.deepEqual([...cr.querySelectorAll('.reader-page')].map(el=>el.dataset.page),['1','2','4']);cross.window.close();
  console.log('PASS: 首楼/评论/楼层、折叠引用、单引用回复链、多引用保留、上下文定位、分页加载/防并发/去重、跨页关系与按需取页、动态更新、安全内容重建、原版恢复、失败回退。');
})().catch(e=>{console.error(e);process.exit(1)});
